// app/components/PostNav.tsx
import { Link } from 'remix';
import { Post } from '~/ts/post-api';

type PostNavProps = {
    previousPost?: Post;
    nextPost?: Post;
};

export default function PostNav({ previousPost, nextPost }: PostNavProps) {
    return (
        <div className="c-post-nav">
            {previousPost && (
                <div className="c-post-nav__link c-post-nav__link--previous">
                    <Link
                        className="c-post-nav__link-arrow"
                        to={previousPost.permalink}
                        title={previousPost.title}>
                        ⏪
                    </Link>
                    &nbsp;
                    <Link
                        to={previousPost.permalink}
                        title={previousPost.title}>
                        {previousPost.title}
                    </Link>
                </div>
            )}

            {nextPost && (
                <div className="c-post-nav__link c-post-nav__link--next">
                    <Link to={nextPost.permalink} title={nextPost.title}>
                        {nextPost.title}
                    </Link>
                    &nbsp;
                    <Link
                        className="c-post-nav__link-arrow"
                        to={nextPost.permalink}
                        title={nextPost.title}>
                        ⏩
                    </Link>
                </div>
            )}
        </div>
    );
}

// components/PostNav.vue
<template>
    <div class="c-post__nav">

        <div v-if="previousPost"
             class="c-post__nav-link c-post__nav-link--previous" >

            <!--
            <nuxt-link :to="previousPost.permalink"
                       :title="previousPost.title">
                <span class="fa fa-arrow-left"></span>
            </nuxt-link>
            -->

            <nuxt-link :to="previousPost.permalink"
                       :title="previousPost.title">
                Previous: {{ previousPost.title }}
            </nuxt-link>

        </div>

        <div v-if="nextPost"
             class="c-post__nav-link c-post__nav-link--next" >

            <nuxt-link :to="nextPost.permalink"
                       :title="nextPost.title">
                Next: {{ nextPost.title }}
            </nuxt-link>

            <!--
            <nuxt-link :to="nextPost.permalink"
                       :title="nextPost.title">
                <span class="fa fa-arrow-right"></span>
            </nuxt-link>
            -->

        </div>

    </div>
</template>

<script>
export default {
    props: {
        previousPost: {
            type: Object,
            default: null,
        },
        nextPost: {
            type: Object,
            default: null,
        },
    },
};
</script>
