// app/components/PostMeta.tsx
import { Link } from 'remix';
import { Post } from '~/post-api';

type PostMetaProps = {
    post: Post;
};

export default function PostMeta({ post }: PostMetaProps) {
    let formattedDate = post.postDate;
    try {
        const date = new Date(post.postDate);
        const [, month, day, year] = date.toDateString().split(' ');
        formattedDate = `${month} ${day}, ${year}`;
    } catch (e) {}

    return (
        <p className="post-meta">
            <span title={formattedDate} className="c-meta__date">
                {post.relativeDate}
            </span>

            <span className="post-meta__divider1">|</span>

            <span>{post.readingTime}</span>

            <br className="post-meta__br" />

            <span className="post-meta__divider2">|</span>

            {post.tags.map((tag) => (
                <span key={tag} className="post-meta__link">
                    <Link to={`/tag/${tag}/`} title={tag}>
                        {tag}
                    </Link>
                </span>
            ))}
        </p>
    );
}

// src/components/PostMeta.vue
<template>
    <div>

        <p class="c-meta__line1">
            <span :title="formattedDate" class="c-meta__date">
                {{ relativeDate }}
            </span>

            <span class="c-meta__divider c-meta__divider--first">|</span>

            <span class="c-meta__readtime">{{ post.readingTime.text }}</span>

        </p>

        <p class="c-meta__line2">

            <span class="c-meta__tags">
                Tags:
                <template v-for="(tag, index) in tagArray">
                    <router-link
                        :key="tag"
                        :to="`/tag/${tag}/`"
                        :title="tag"><!--
                        -->{{ tag }}<!--
                    --></router-link><!--
                    --><template v-if="index < tagArray.length - 1">, </template>
                </template>
            </span>

        </p>

    </div>
</template>

<script>
import { isString } from 'lodash-es';
import vagueTime from 'vague-time';

export default {
    props: {
        post: {
            type: Object,
            required: true,
        },
    },
    computed: {
        postDate() {
            return new Date(Date.parse(this.post.postDate));
        },
        relativeDate() {
            return vagueTime.get({ to: this.postDate.getTime() });
        },
        formattedDate() {
            const [ , month, date, year ] = this.postDate.toDateString().split(' ');
            return `${month} ${date}, ${year}`;
        },
        tagArray() {
            return isString(this.post.tags) ?
                this.post.tags.split(',') :
                [];
        },
    },
};
</script>

<style lang="scss">
.c-meta {

    &__line1 {
        padding-bottom: 0.5rem;
    }

    &__date {

    }

    &__divider {
        padding: 0 10px;
    }

    &__tags {

    }

    &__readtime {

    }

}
</style>
