// app/components/SiteInfo.tsx
import ExternalLink from './ExternalLink';

interface LinkLine {
    href: string;
    title: string;
}
type Line = LinkLine | string;

export default function SiteInfo() {
    const lines: Line[][] = [
        [
            'built with ',
            {
                href: 'https://reactjs.org/',
                title: 'react',
            },
            ' and ',
            {
                href: 'https://remix.run/',
                title: 'remix',
            },
        ],
        [
            'stored in ',
            {
                href: 'https://www.github.com/brophdawg11/brophy.org-remix',
                title: 'github',
            },
            ', hosted in ',
            {
                href: 'https://fly.io/',
                title: 'fly.io',
            },
        ],
        [
            'icons from ',
            {
                href: 'https://fontawesome.com/',
                title: 'font-awesome',
            },
            ' via ',
            {
                href: 'http://fontello.com/',
                title: 'fontello',
            },
        ],
    ];
    const year = new Date().getFullYear();

    return (
        <div>
            {lines.map((line, index) => (
                <p key={index} className="page-footer-line">
                    {line.map((text, index2) =>
                        typeof text === 'string' ? (
                            <span key={index2}>{text}</span>
                        ) : (
                            <ExternalLink key={index2} href={text.href}>
                                {text.title}
                            </ExternalLink>
                        )
                    )}
                </p>
            ))}

            <p className="page-footer-line">
                &copy; Copyright {year} Matt Brophy
            </p>
        </div>
    );
}

// src/components/SiteInfo.vue
<template>
    <div v-once>
        <p class="page-footer-line">
            built with
            <ExternalLink href="https://vuejs.org/" title="Vue">
                vue
            </ExternalLink>
            and
            <ExternalLink href="https://ssr.vuejs.org/en/" title="Vue SSR">
                vue ssr
            </ExternalLink>
        </p>
        <p class="page-footer-line">
            hosted on
            <ExternalLink href="https://firebase.google.com/" title="Firebase">
                firebase
            </ExternalLink>
            using
            <ExternalLink href="https://firebase.google.com/products/functions/"
                          title="Cloud Functions">
                cloud functions
            </ExternalLink>
        </p>
        <p class="page-footer-line">
            stored in
            <ExternalLink href="https://www.github.com/brophdawg11/brophy.org"
                          title="GitHub">
                github
            </ExternalLink>
        </p>
        <p class="page-footer-line">
            side images from
            <ExternalLink href="https://www.gratisography.com/" title="Gratisography">
                gratisography
            </ExternalLink>
        </p>
        <p class="page-footer-line">
            icons from
            <ExternalLink href="https://fontawesome.com/"
                          title="Font-Awesome">
                font-awesome
            </ExternalLink>
            via
            <ExternalLink href="http://fontello.com/" title="Fontello">
                fontello
            </ExternalLink>
        </p>
        <p class="page-footer-line">
            &copy; Copyright {{ year }} Matt Brophy
        </p>

    </div>
</template>

<script>
import ExternalLink from '@components/ExternalLink.vue';

export default {
    name: 'SiteInfo',
    components: {
        ExternalLink,
    },
    data() {
        return {
            year: new Date().getFullYear(),
        };
    },
};
</script>

<style lang="scss">
.page-footer-line {
    line-height: 1.5em;
    padding: 0.25em;
}
</style>
